# Generated by Django 4.2.4 on 2023-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_colorpalette_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
