# Generated by Django 4.2.4 on 2023-08-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_colorpalette_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
